### ISSUE TITLE
Foscam V2 Error Logsettings

### ISSUE THREAD

**Issue by thundergreen** [ReneTode/My-AppDaemon#4]
Hi Rene. Thanks so much for your efforts.. but what is this?

```
pi@chilipie-kiosk:~/conf/logs$ tail -f appdaemon_error.log
2017-10-11 00:51:48.830596 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 911, in read_app
    init_object(name, class_name, module_name, conf.app_config[name])
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 582, in init_object
    conf.objects[name]["object"].initialize()
  File "/home/pi/conf/apps/foscam.py", line 37, in initialize
    self.logsettings = self.args["logsettings"]
KeyError: 'logsettings'
```

**Comment by thundergreen** [comment]
```
pi@chilipie-kiosk:~/conf/logs$ tail -f appdaemon.log
2017-10-11 00:57:35.204557 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/dashboard.py", line 803      , in get_dashboard
    with open(include_path, "r") as include_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/conf/compiled/      html/default/dash_terrascam_head.html'
```

**Comment by ReneTode** [comment]
settings in apps.yaml were not right.
