### ISSUE TITLE
Help to Install

### ISSUE THREAD

**Issue by nlienard** [ReneTode/My-AppDaemon#8]
Hello

This is my first usage of appdaemon so i'm a bit confused.

1. in apps/ folder i put foscam.py which is clear from the installation doc
2. in conf/ folder i put apps.yaml and i modified camera_name , host, port, user, password

3. i added widgets

       thoht@osmc:~/.homeassistant/appdaemon$ ls -la conf/custom_widgets/
       total 16
       drwxr-xr-x 2 thoht thoht 4096 mars   1 12:31 .
       drwxr-xr-x 5 thoht thoht 4096 mars   1 13:13 ..
       -rw-r--r-- 1 thoht thoht  664 mars   1 12:30 new_input_slider.yaml
       -rw-r--r-- 1 thoht thoht  704 mars   1 12:31 vertical_input_slider.yaml

4. foscam.yaml is very simiar to apps.yaml , i don't know where to put it.

For now, i got the following error:

     018-03-01 13:17:27.439112 WARNING AppDaemon:      ------------------------------------------------------------
     2018-03-01 13:17:27.441579 WARNING AppDaemon: ------------------------------------------------------------
     2018-03-01 13:17:27.442241 WARNING AppDaemon: Unexpected error during utility()
     2018-03-01 13:17:27.442931 WARNING AppDaemon:      ------------------------------------------------------------
     2018-03-01 13:17:27.444352 WARNING AppDaemon: Traceback (most recent call last):
       File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1305, in utility
         await utils.run_in_executor(self.loop, self.executor, self.check_app_updates)
       File "/usr/local/lib/python3.6/site-packages/appdaemon/utils.py", line 121, in run_in_executor
         response = list(completed)[0].result()
       File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
         result = self.fn(*self.args, **self.kwargs)
       File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1751, in      check_app_updates
         if apps["term"]:
     TypeError: 'NoneType' object is not subscriptable

**Comment by nlienard** [comment]
i close this issue as my appdaemon is version 3 ans this git is for appdaemon v2
I've opened another issue on the good repo.
